server:
  port: 8001

spring:
  application:
    name: cloud-provider-payment-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
      #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
      #    url: jdbc:mysql://localhost:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/springcloud2020?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapperLocations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto