spring:
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        group: nacos-8100 # 在此处配置不生效 必须要配置到  bootstrap里



server:
  port: 8100
lhp:
  name: application.yaml
  name_aa: application.yaml

# 配置文件优先级  配置中心> application.yaml>bootstrap.properties
