server:
  port: 80


spring:
  application:
    name: cloud-consumer-openfeign-order
eureka:
  instance:
    prefer-ip-address: true
    instance-id: order80
  client:
    register-with-eureka: false
    # 集群必须设置为 true 单点无所谓 否则无法使用ribbon负载均衡
    service-url:
    #  defaultZone: http://localhost:7001/eureka  http://eureka7002.com:7002/eureka/
       defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000